services:
  clientapp:
    image: thy015/takeabreath:client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - ./client:/app

  serverapp:
    image: thy015/takeabreath:server
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - ./server:/app

networks:
  app-network:
    driver: bridge
